# Generated by Django 5.0.5 on 2024-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'dob')},
        ),
    ]
