# Generated by Django 5.0.5 on 2024-05-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
        ('cart', '0002_alter_cart_created_at_alter_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_status',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'book')},
        ),
    ]
