# Generated by Django 5.0.5 on 2024-05-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_geo_address_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo',
        ),
    ]
