# Generated by Django 5.0.5 on 2024-05-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default='2022-02-25'),
        ),
    ]
