# Generated by Django 5.0.5 on 2024-05-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_price_orderitem_price_orderitem_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='userId',
        ),
    ]
