# Generated by Django 5.0.5 on 2024-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_quantity',
            field=models.FloatField(default=0),
        ),
    ]
